/*
 * The MIT License
 *
 * Copyright 2016 david.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package rgbtopng;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author david
 */
public class RGBHistoryGenerator {
    //declare an ArrayList of strings to store the RGB values in the recent
    //history and a n integer value to count how many real values are being stored
    private ArrayList<String> rgbHistory = new ArrayList<>(5);
    int historyCount = 0;
    
    //write the history of RGB colors generated by the user to a file
    public void writeRGBHistory()    {
        FileOutputStream fos;
        ObjectOutputStream outputStream;
        
        //TODO implement file writing
    }
    
    //reads the history of RGB colors from a previously generated history file
    public String[] readRGBHistory() throws FileNotFoundException, IOException, ClassNotFoundException    {
        //declare and initialize variables relating to reading in and returning
        //imported RGB history from file
        ArrayList<String> importedRGBHistory = new ArrayList<>(5);
        String[] rgbHistoryArray = new String[5];
        FileInputStream fis = new FileInputStream("rgbHistory.rgbh");
        ObjectInputStream inputStream = new ObjectInputStream(fis);
        
        //read in the serialized ArrayList to importedRGBHistory for conversion
        //to an array for the application to use to display recently generated colors 
        importedRGBHistory = (ArrayList<String>) inputStream.readObject();
        
        //copy values from the imported ArrayList to array that will be returned
        for(int i = 0; i < rgbHistoryArray.length; i++) {
            rgbHistoryArray[i] = importedRGBHistory.get(i);
        }
        
        //return an array of the five most recently generated colors
        return rgbHistoryArray;
    }
    
    //add a color to the history
    public void addRGBHistory(String rgbVal)    {
        //add a new RGB value to the history ArrayList
        this.rgbHistory.add(rgbVal);
    }
}
